version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - ai-service

  ai-service:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    environment:
      - MODEL_PATH=/app/models
      - AI_PROVIDER=local
    volumes:
      - ./ai-services/models:/app/models
      - ./ai-services/cache:/app/cache
    deploy:
      resources:
        reservations:
          memory: 8G
    ports:
      - "8000:8000"

  model-service:
    build:
      context: ./model-services
      dockerfile: Dockerfile.model
    environment:
      - MODEL_NAME=mistral-7b-instruct-v0.1.Q4_K_M.gguf
    volumes:
      - ./model-services/models:/models
    deploy:
      resources:
        reservations:
          memory: 8G
    ports:
      - "8001:8001"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - ai-service 